ID command - NCPlayz' Cog
dpy-blobs/AssBot pull request #146
Opened 2017-09-06 19:41 UTC by NCPlayz

2017-09-06 19:46 UTC, ReinaSakuraba requested changes
Use converters instead of what you're using now

2017-09-06 19:46 UTC, NCPlayz commented
ok

2017-09-06 22:13 UTC, BlackSynder commented on cogs/ncplayz.py
> +            msg = "**Error!** A channel named {0} could not be found! You must enter the exact name (including caps).".format(request)
NameError here (and in other cmds) for request

2017-09-06 22:13 UTC, BlackSynder commented on cogs/ncplayz.py
> +        """Fetches the ID of the server """
be consistent, you give a choice (default value) in the rest of the commands but omit it in server.

2017-09-06 22:28 UTC, Ikusaba-san commented on cogs/ncplayz.py
> +    async def channel(self, ctx, *, channel: discord.Channel = None):
We're using rewrite, so `discord.Channel` is not a thing.

2017-09-06 22:31 UTC, Ikusaba-san commented on cogs/ncplayz.py
> +        if role:
You don't need these `if` statements. If the conversion fails, usually because it wasn't found. It raises `commands.BadArgument`.

2017-09-07 06:36 UTC, NCPlayz commented
Just seen the comments - will fix as soon as possible. Thanks.

2017-09-12 20:34 UTC, closed without merging